### ISSUE TITLE
Divide higherOrder in Genuine and Convenience

### ISSUE THREAD

**Issue by marvinwest** [zesch/linguistic-features-in-text#3]
Genuine -> FeatureExtractors that can´t be built by only using lower order Extractors.

Convenience -> FeatureExtractors built using lower order Extractors in a meaningful way, e. g. VerbPerSentence from AvgAnnotationRatio. See Escrito or FE_AvgAnnotationRetioTest for meaningful uses of AvgAnnotationRatio.

**Comment by zesch** [comment]
Package structure is likely to change anyway.
