### ISSUE TITLE
Naming Feature in genericStructureCounter

### ISSUE THREAD

**Issue by marvinwest** [zesch/linguistic-features-in-text#9]
In the genericStructureCounter, we use the internalName to name the extracted feature. The String in the internalName is cleaned from Java-Identifiers, therefore if I want to count Structure REGEXP_; and REGEXP_, both have the same feature-Name (org_lift_features_FEL_GenericStructureCounter_REGEXP__) and I can not use it properly going forward. Why don´t we use the publicname for the extracted Feature, which would lead to REGEXP_;_counter and REGEXP_,_counter.

**Comment by zesch** [comment]
Naming scheme of FEs will be overhauled completely.

**Comment by zesch** [comment]
clown
